name: 'Release Manager'
description: 'Manage GitHub releases'
author: 'YoloDev'
inputs:
  token:
    required: false
    description: GitHub token
    default: ${{ github.token }}

  label:
    required: false
    description: GitHub issue label to use to identify release issues
    default: ':shipit: release'

  dry-run:
    required: false
    description: Whether to only simulate the changes applied by this action
    default: 'false'

runs:
  using: 'node12'
  main: 'dist/index.js'
